### PR TITLE
Login logout functionality

### PR DESCRIPTION
**Pull request by LangeJM**
In prep for the login/logout functionality, converted App.js to class for login/ logout state management and reverted about.jsx back to function

### CODE REVIEW

**Comment by lieblichaaron** [comment]
try to make more commits, please. makes it much harder to read through without them. no need to push changes to the navbar right now, if you need to see how it looks at another state just change it on your computer and switch them back before the push. can you split the page into separate components and merge again, also add all the pictures you uploaded to one folder.

**Comment by lieblichaaron** [comment]
Sorry for leaving a bunch of comments but Im also not sure we need a state for the app.js to be logged in. If the client has a cookie that we can identify that's all that needs to be checked for log in status. then for each page we can make a unique request to the server for the info needed on that page.

**Comment by LangeJM** [comment]
> Sorry for leaving a bunch of comments but Im also not sure we need a state for the app.js to be logged in. If the client has a cookie that we can identify that's all that needs to be checked for log in status. then for each page we can make a unique request to the server for the info needed on that page.

I would like to leave it in for now, consider it a placeholder that has functionality if needed. It's really easy to change it to cookie/session managed later on, which we also need to agree on how to best organize that.

**Comment by LangeJM** [comment]
> try to make more commits, please. makes it much harder to read through without them. no need to push changes to the navbar right now, if you need to see how it looks at another state just change it on your computer and switch them back before the push. can you split the page into separate components and merge again, also add all the pictures you uploaded to one folder.

All the pictures are in one folder though?!
I will extract the carousel from the component and import.

**Comment by lieblichaaron** [comment]
the pictures are in the public folder along with the index.html, I just think it would be clearer if you had an images folder in the public containing all the images.

**Comment by LangeJM** [comment]
> the pictures are in the public folder along with the index.html, I just think it would be clearer if you had an images folder in the public containing all the images.

Now I got it, no problem!

**Pull request closed without merging**
